import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './navbar'
import bg from '../public/background.jpg'

export default function Home() {
  return (
    <div style={{ backgroundImage: `url(${bg.src})`, height: '1080px' }} >
      <Head>
        <title>League of legends Let battle commence…</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.board}>
        <Image src="/board.png" width="693px" height="194px" />
      </div>
      <div className={styles.details_btn}>
        <Image src="/details_btn.png" width="298px" height="29px" />
      </div>
      <button className={styles.games_btn}>
        <Image src="/all_games_btn.png" width="385px" height="61px" />
      </button>
    </div>
  )
}
